[Interface]
PrivateKey = YMTgjYdZC7fyebRk6crNqPQbgPYoTOnoS7rbeBck2nI=
Address = fd08:5408:3067::9/128

[Peer]
PublicKey = spAIyvwsnZyqb/E5Am8FMnxDgDBNR5uh4XK35GgRvnY=
Endpoint = 125.228.136.19:54088
AllowedIPs = fd08::/16
