return {}
-- return {
--     {
--         "neo-tree.nvim",
--         keys = {
--             {
--                 "<leader>ft",
--                 function()
--                     require("neo-tree.command").execute({ toggle = true })
--                 end,
--                 desc = "Toggle Neo-tree",
--             },
--         },
--         before = function()
--             require("lz.n").load("plenary.nvim")
--             require("lz.n").load("nui.nvim")
--             require("lz.n").load("nvim-web-devicons")
--         end,
--         after = function()
--             require("neo-tree").setup({
--                 window = {
--                     mappings = {
--                         ["q"] = "close_window",
--                     },
--                 },
--                 close_if_last_window = true,
--                 popup_border_style = "rounded",
--
--                 filesystem = {
--                     follow_current_file = {
--                         enabled = true, -- This will find and focus the file in the active buffer every time
--                         leave_dirs_open = true, -- `false` closes auto expanded dirs, such as with `:Neotree reveal`
--                     },
--                 },
--                 event_handlers = {
--                     {
--                         event = "file_open_requested",
--                         handler = function()
--                             -- auto close
--                             -- vim.cmd("Neotree close")
--                             -- OR
--                             require("neo-tree.command").execute({ action = "close" })
--                         end,
--                     },
--                 },
--             })
--         end,
--     },
--     { "nui.nvim" },
--     { "plenary.nvim" },
--     { "nvim-web-devicons" },
-- }
